### PR TITLE
add Vector functions

### PR DESCRIPTION
**Pull request by battlecook**

### CODE REVIEW

**Comment by mcordingley** [comment]
I have gone back and forth on having a separate `Vector` class for this library, since a vector is just a matrix with only one row or one column. Just to give me some context, how are you intending to use this new class? Aside from that, what does including this class add that `Matrix` is unable to provide?

**Comment by battlecook** [comment]
Thank you for your reply.
First of all, I apologize for poor English. 
I thought the Vector have a special operation like dot product.
so I just added the Vector class and separated from the Matrix class.
When clients use this lib, I want them to notice whether this is Vector or Matrix.

**Comment by mcordingley** [comment]
It's OK. I struggle with other languages, so I figure that you're one up on me for having English down as well as you do.

I think you're onto something with having a Vector class so clients can make finer grained assertions. But, a vector is a matrix. So, the class hierarchy should reflect that. I like to keep my public interfaces as locked down as I possibly can, so let me first tweak the Matrix class to be extendable only in the ways you need for `Vector` to inherit from it.

**Comment by battlecook** [comment]
Aha!I understood your thinking.
I found that the Matrix Class is specified with final keyword.
So I thought you don't want to inherit the Matrix Class.
I re-commited to reflect class hierarchy.

**Comment by mcordingley** [comment]
Yeah, it's easy to remove `final` or increase the visibility of a method. It's hard to go in reverse. So I lock it down with the understanding that I could loosen it up if needed.

I skimmed through your commits and it looks like we're getting closer. I'll try to take a closer look soon with more specific feedback. Your code style is looking clean, by the way.

**Comment by mcordingley** [comment]
I just got back from being out of state for a while. I'll review this as soon as I can.

**Comment by mcordingley** [comment]
I'm looking through right now. There are some changes that I want to make to your pull, but it'll be faster and easier to simply make them directly than to try to bounce them back to you. Hold tight.

**Comment by mcordingley** [comment]
I pulled your changes here https://github.com/mcordingley/LinearAlgebra/tree/battlecook-master and then added some of my own. All tests pass and everything looks good to me. If it also looks good to you, I'll go ahead and tag a new release.

**Comment by battlecook** [comment]
Thank you for your review.
I am going to read this code as soon as possible.

**Comment by battlecook** [comment]
I read all changed including commit comment, history in detail. Now the code becomes clean for your commit. and It also looks good to me.

**Comment by mcordingley** [comment]
Great. I'll merge it and tag a minor release this weekend.

**Comment by mcordingley** [comment]
I ended up having time today, so this is now published as version 2.1.0. Thanks again!

**Pull request merged**
